import {
  Package,
  BarChart3,
  FileText,
  Truck,
  Boxes,
  QrCode,
  ArrowDownUp,
  ClipboardList,
  Receipt,
  FileCheck,
  FilePlus,
  MessageSquare,
  Landmark,
  Copy,
  TrendingUp,
  PieChart,
  Activity,
  Target,
  Users,
  ShoppingCart,
  MapPin,
  CalendarClock,
  Settings,
  LayoutDashboard,
  LucideIcon,
  Store,
  Tag,
  Globe,
  Wrench,
  ShoppingBag,
  UserCog,
  Wallet,
  Building2,
  ArrowLeftRight,
  Calculator,
  ClipboardCheck,
  ListTodo,
  KanbanSquare,
  ListChecks,
  CalendarDays,
  Bell,
  CalendarOff,
  ClipboardList as ClipboardListIcon,
  Star,
  Upload,
  DollarSign,
  Repeat,
} from "lucide-react";

export interface WorkspaceItem {
  title: string;
  url: string;
  icon: LucideIcon;
}

export interface Workspace {
  id: string;
  label: string;
  icon: LucideIcon;
  description: string;
  items: WorkspaceItem[];
}

export const workspaces: Workspace[] = [
  {
    id: "entrepot",
    label: "Entrepôt",
    icon: Boxes,
    description: "Gestion du stock et inventaire",
    items: [
      { title: "Vue d'ensemble", url: "/entrepot/dashboard", icon: LayoutDashboard },
      { title: "Inventaire", url: "/entrepot/inventaire", icon: ClipboardList },
      { title: "Mouvements", url: "/entrepot/mouvements", icon: ArrowDownUp },
      { title: "Codes-barres", url: "/entrepot/codes-barres", icon: QrCode },
      { title: "Catégories", url: "/entrepot/categories", icon: Package },
      { title: "Étiquettes", url: "/entrepot/etiquettes", icon: Tag },
      { title: "Doublons", url: "/entrepot/doublons", icon: Copy },
      { title: "Maintenance", url: "/entrepot/maintenance", icon: Wrench },
      { title: "Paramètres", url: "/entrepot/parametres", icon: Settings },
    ],
  },
  {
    id: "commerce",
    label: "Commerce",
    icon: Receipt,
    description: "Facturation et documents commerciaux",
    items: [
      { title: "Vue d'ensemble", url: "/commerce/dashboard", icon: LayoutDashboard },
      { title: "Caisse", url: "/commerce/caisse", icon: Calculator },
      { title: "Factures", url: "/commerce/factures", icon: FileText },
      { title: "Devis", url: "/commerce/devis", icon: FilePlus },
      { title: "Bons de livraison", url: "/commerce/bons-livraison", icon: FileCheck },
      { title: "Clients", url: "/commerce/clients", icon: Users },
      { title: "Demandes", url: "/commerce/demandes", icon: MessageSquare },
      { title: "Produits repris", url: "/commerce/produits-repris", icon: ArrowLeftRight },
      { title: "Créances", url: "/commerce/creances", icon: Landmark },
      { title: "Achats quotidiens", url: "/commerce/achats", icon: ShoppingBag },
      { title: "Factures récurrentes", url: "/commerce/recurrentes", icon: Repeat },
      { title: "Import produits", url: "/commerce/import-produits", icon: Upload },
      { title: "Doublons clients", url: "/commerce/doublons-clients", icon: Copy },
      { title: "Paramètres", url: "/commerce/parametres", icon: Settings },
    ],
  },
  {
    id: "logistique",
    label: "Logistique",
    icon: Truck,
    description: "Fournisseurs et approvisionnement",
    items: [
      { title: "Vue d'ensemble", url: "/logistique/dashboard", icon: LayoutDashboard },
      { title: "Fournisseurs", url: "/logistique/fournisseurs", icon: Users },
      { title: "Notations", url: "/logistique/notations", icon: Star },
      { title: "Commandes", url: "/logistique/commandes", icon: ShoppingCart },
      { title: "Livraisons", url: "/logistique/livraisons", icon: MapPin },
      { title: "Planification", url: "/logistique/planification", icon: CalendarClock },
    ],
  },
  {
    id: "boutique",
    label: "Boutique",
    icon: Store,
    description: "Boutique en ligne et commandes",
    items: [
      { title: "Vue d'ensemble", url: "/boutique/dashboard", icon: LayoutDashboard },
      { title: "Catalogue", url: "/boutique/catalogue", icon: Package },
      { title: "Commandes", url: "/boutique/commandes", icon: ShoppingCart },
      { title: "Promotions", url: "/boutique/promotions", icon: Tag },
      { title: "Site web", url: "/boutique/site-web", icon: Globe },
      { title: "Paramètres", url: "/boutique/parametres", icon: Settings },
    ],
  },
  {
    id: "personnel",
    label: "Personnel",
    icon: UserCog,
    description: "Gestion du personnel et salaires",
    items: [
      { title: "Vue d'ensemble", url: "/personnel/dashboard", icon: LayoutDashboard },
      { title: "Employés", url: "/personnel/employes", icon: Users },
      { title: "Salaires", url: "/personnel/salaires", icon: Wallet },
      { title: "Congés", url: "/personnel/conges", icon: CalendarOff },
      { title: "Présences", url: "/personnel/presences", icon: ClipboardListIcon },
    ],
  },
  {
    id: "banque",
    label: "Banque",
    icon: Building2,
    description: "Gestion bancaire et tresorerie",
    items: [
      { title: "Vue d'ensemble", url: "/banque/dashboard", icon: LayoutDashboard },
      { title: "Comptes", url: "/banque/comptes", icon: Wallet },
      { title: "Transactions", url: "/banque/transactions", icon: ArrowLeftRight },
      { title: "Virements", url: "/banque/virements", icon: ArrowDownUp },
      { title: "Conversion", url: "/banque/conversion", icon: Calculator },
      { title: "Rapprochement", url: "/banque/rapprochement", icon: ClipboardCheck },
      { title: "Import CSV", url: "/banque/import", icon: Upload },
      { title: "Parametres", url: "/banque/parametres", icon: Settings },
    ],
  },
  {
    id: "analytique",
    label: "Analytique",
    icon: BarChart3,
    description: "Rapports et tableaux de bord",
    items: [
      { title: "Tableau de bord", url: "/analytique/dashboard", icon: LayoutDashboard },
      { title: "Tendances", url: "/analytique/tendances", icon: TrendingUp },
      { title: "Répartition", url: "/analytique/repartition", icon: PieChart },
      { title: "Rentabilité", url: "/analytique/rentabilite", icon: DollarSign },
      { title: "Objectifs", url: "/analytique/objectifs", icon: Target },
    ],
  },
  {
    id: "taches",
    label: "Pilotage",
    icon: ListTodo,
    description: "Gestion des tâches et projets",
    items: [
      { title: "Vue d'ensemble", url: "/taches/dashboard", icon: LayoutDashboard },
      { title: "Tableaux", url: "/taches/tableaux", icon: KanbanSquare },
      { title: "Toutes les tâches", url: "/taches/liste", icon: ListChecks },
      { title: "Agenda", url: "/taches/agenda", icon: CalendarDays },
    ],
  },
];
